### ISSUE TITLE
CNN for 3D

### ISSUE THREAD

**Issue by charujing** [XanaduAI/qml#70]
Hi,
     The tutorial_quanvolution.py is very useful for the quantum CNN in 2D data, such as images. Does anyone know materials or tutorials that could be used for the 3D quantum CNN?
    Thanks very much. 
    All the best.
Rujing

**Comment by co9olguy** [comment]
Hi @charujing, and thanks for the question. 

My first thought was that the best person to answer this would be the inventor of the quanvolutional neural network. Let's see if we can summon him with a mention here (his GitHub handle seems to be @Spider2themax)

**Comment by Spider2themax** [comment]
Hey @charujing ! I can definitely answer this (thanks for the ping @co9olguy 👍 )

So you can absolutely use QNN implements for 3D tensor image input as well; really you just have to ensure that the encoding protocol is designed to handle that. In a recent paper we published (https://arxiv.org/abs/2004.03079), we processed 3D images by taking N-by-N-by-M tensor blocks, and mapping the values to single qubit gate rotations. I'd read over our approach in this paper to see if it makes sense, and I am sure a similar approach could be useful for your work.

**Comment by charujing** [comment]
Hi @co9olguy  and @Spider2themax 
     Thanks very much for your reply and help. Great! I will try.
     All the best.

**Comment by co9olguy** [comment]
Thanks @Spider2themax!
